services:
  #Base de Datos PostgreSQL
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: cL4w5pVz

    #Interfaz de Base de Datos
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080